name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd /opt/test
          git pull https://github.com/ADrakey/test.git
